### PR TITLE
fix broken simutils install

### PR DESCRIPTION
**Pull request by macrozone**
again https://github.com/pniko/detox-appcenter/pull/21

i don't see why there was a conflict there

### CODE REVIEW

**Comment by henrikra** [comment]
@pniko Want to check this out? I have the same code as in this PR and it works 🎉

**Comment by pniko** [comment]
Not sure what was up with that PR either. This one looks good - thanks for the change!

**Comment by henrikra** [comment]
Great! Can you also check the issue about Android?

**Comment by pniko** [comment]
@henrikra  Just asked someone on my team to look at that tonight. Will see if we can keep the sample updated.

**Pull request merged**
